In [1]:
import nltk
import pandas as pd
import io
import re
from string import punctuation
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from random import shuffle
#nltk.download('punkt')
#nltk.download('stopwords')
#nltk.download('PorterStemmer')

In [2]:
data = pd.read_csv('cleanerstill.csv', sep=";")
data.head()

C:\Users\xetrev\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,age,body type,diet,drinks,drugs,education,essay0,essay4,essay6,essay7,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22,a little extra,strictly anything,socially,never,working on college university,about me i would love to think that i was so...,books absurdistan the republic of mice and ...,duality and humorous things,trying to find someone to hang out with i am ...,...,south san francisco california,doesnt have kids but might want them,straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35,average,mostly other,often,sometimes,working on space camp,i am a chef this is what that means 1 i am ...,i am die hard christopher moore fan i don't r...,,,...,oakland california,doesnt have kids but might want them,straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,english fluently spanish poorly french ...,single
2,38,thin,anything,socially,,graduated from masters program,i'm not ashamed of much but writing public te...,okay this is where the cultural matrix gets so...,,viewing listening dancing talking drinking...,...,san francisco california,,straight,has cats,,m,pisces but it doesnt matter,no,english french c,available
3,23,thin,vegetarian,socially,,working on college university,i work in a library and go to school,bataille celine beckett lynch jarmusch...,cats and german philosophy,,...,berkeley california,doesnt want kids,straight,likes cats,,m,pisces,no,english german poorly,single
4,29,athletic,,socially,never,graduated from college university,hey how's it going currently vague on the prof...,music bands rappers musicians at the moment...,,,...,san francisco california,,straight,likes dogs and likes cats,,m,aquarius,no,english,single

In [16]:
mask = (data['ethnicity'] != ' ') & (type(data['ethnicity']) != float) & (data['age'] != ' ') & (data['sex'] != ' ')
# mask removes all rows where ethnicity, age and sex is not given. Also removes rows where ethnicity is NaN. This particular value is not present for age and sex, hence it is not masked out.
data_new = data[mask]

data_relv_columns = data_new.filter(['age','sex','ethnicity','essay0','essay4'], axis=1)

data_relv_columns

,age,sex,ethnicity,essay0,essay4
0,22,m,asian white,about me i would love to think that i was so...,books absurdistan the republic of mice and ...
1,35,m,white,i am a chef this is what that means 1 i am ...,i am die hard christopher moore fan i don't r...
3,23,m,white,i work in a library and go to school,bataille celine beckett lynch jarmusch...
4,29,m,asian black other,hey how's it going currently vague on the prof...,music bands rappers musicians at the moment...
5,29,m,white,i'm an australian living in san francisco but...,books to kill a mockingbird lord of the ring...
...,...,...,...,...,...
59938,31,f,middle eastern,real deal i am sensitive sorry tears includ...,too many to name a new earth kite runner...
59940,24,m,white other,i'm nick i never know what to write about mys...,movies hook the greatest adventure ever gl...
59941,42,m,asian,hello i enjoy traveling watching movies and ...,last book game change movies bourne serie...
59942,27,m,asian black,all i have in this world are my balls and my ...,where to begin musically right now i listen t...
59943,39,m,white,is it odd that having a little enemy status ...,i just read the help by kathryn stockett sooo...